name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Clone the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Enable multi-platform builds

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Convert repository name to lowercase
      run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]' | cut -d'/' -f2)" >> $GITHUB_ENV

    - name: Build and tag the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest .
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}

    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}

