name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Clone the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Enable multi-platform builds

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert repository name to lowercase
      run: echo "REPO_NAME=$(echo ${{ github.repository_owner }}/$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_-'))" >> $GITHUB_ENV

    - name: Build and tag the Docker image
      run: |
        docker build -t ghcr.io/${{ env.REPO_NAME }}/random-number-app:latest .
        docker tag ghcr.io/${{ env.REPO_NAME }}/random-number-app:latest ghcr.io/${{ env.REPO_NAME }}/random-number-app:${{ github.sha }}

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ env.REPO_NAME }}/random-number-app:latest
        docker push ghcr.io/${{ env.REPO_NAME }}/random-number-app:${{ github.sha }}
